version: '2'
services:
    php7:
        build: ./docker/container/php7
        ports:
            - 9010-9015:9010-9015
        volumes:
            - ./:/var/www
            - ./docker/etc/php/7.2/cli/php.ini:/etc/php/7.2/cli/php.ini
            - ./docker/etc/php/7.2/fpm/php.ini:/etc/php/7.2/fpm/php.ini
            - ./docker/etc/php/7.2/fpm/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
            - ./docker/etc/php/7.2/fpm/pool.d:/etc/php/7.2/fpm/pool.d
            - ./docker/log/php:/var/log/php
        links:
            - mysql
        env_file: .env
    mysql:
        image: percona:5.7
        ports:
            - 3306:3306
        volumes:
            - ./docker/etc/mysql/conf/my.cnf:/etc/mysql/my.cnf
            - ./docker/etc/mysql/conf/mysqld.cnf:/etc/mysql/percona-server.conf.d/mysqld.cnf
            - ./docker/mysql/install.sql:/docker-entrypoint-initdb.d/install.sql:ro
            - ./docker/log/mysql:/var/log/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/etc/nginx/conf.d/sites-enabled:/etc/nginx/conf.d
            - ./docker/etc/nginx/ssl:/etc/nginx/ssl
            - ./:/var/www
            - ./docker/log/nginx:/var/log/nginx
        links:
            - php7
volumes:
    mysql:
